dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - python setup.py -q install 
  - pip install --upgrade pytest pytest-pep8 pytest-cov codecov
script:
  - pytest --cov-config .coveragerc --cov=./
after_success:
  - codecov
